download-integration-tests: clean-integration-tests
    #!/usr/bin/env sh
    TESTS_TAG=$(cat spec-test-version)
    REPO_NAME=consensus-spec-tests
    CONFIGS="general minimal mainnet"
    mkdir ${REPO_NAME}
    for config in ${CONFIGS}
    do
        wget https://github.com/ethereum/${REPO_NAME}/releases/download/${TESTS_TAG}/${config}.tar.gz
        tar -xzf ${config}.tar.gz -C ../${REPO_NAME}
    done
    rm -f *tar.gz

clean-integration-tests:
    rm -rf consensus-spec-tests

fmt:
    cargo +nightly fmt --all

gen-tests:
    cargo run --bin test-gen
    just fmt
